import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import HeroBanner from '@/components/HeroBanner'
import FooterBanner from '@/components/FooterBanner'
import { client } from '@/client'
import Product from '@/components/Product'

const inter = Inter({ subsets: ['latin'] })

export default function Home({ 
  product,
  bannerData
}) {
  console.log(product);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroBanner heroBanner={bannerData.length && bannerData[0]} />
      {console.log(bannerData)}
      <main>
        <div>
          <h2>
            Best Selling Products
          </h2>
          <p>
            Watches of many wariation
          </p>
        </div>
        <div
        // className={styles.productContainer}
        >
          {product?.map(
            (product) => 
              <Product 
                key={product._id}
                product={product}
            />)}
        </div>
      </main>
      <FooterBanner
      footerBanner={bannerData && bannerData[0]}
      />
    </>
  );
  
}

export async function getServerSideProps() {
  const product = await client.fetch(
    `*[_type == "product"]{
      slug,
      name,
      price,
      "imageUrl": image[0].asset->url
    }`
  )

  const bannerData = await client.fetch(
    `*[_type == "banner"]{ largeText1, largeText2, midText, smallText, desc, buttonText, product, saleTime, "imageUrl": image.asset->url}`
  )
  return {
    props: {
      product,
      bannerData
    },
  }
}